packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@effect/ai-openai-compat': 4.0.0-beta.35
  '@effect/platform-node': 4.0.0-beta.34
  '@types/node': ^25
  dotenv: ^17.3.1
  dotenv-cli: ^11.0.0
  effect: 4.0.0-beta.34
  tsx: ^4.21.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
